version: '3'
services:
  sso_mikroservis:
    image: sso_mikroservis
    container_name: sso_mikroservis
    build:
      context: .
      dockerfile: ./sso_test/Dockerfile
    restart: on-failure
    ports:
      # - "8000:${SSO_PORT}"
      - "8000:8000"
    env_file:
      - ./sso_test/.env
    networks:
      mup_mupnet:
        ipv4_address: 10.5.0.9
  tuzilastvo_server:
    image:   tuzilastvo_server
    container_name:   tuzilastvo_server
    build:
      context: .
      dockerfile: ./tuzilastvo/server/Dockerfile
    restart: on-failure
    ports:
      - "8010:8010"
    env_file:
      - ./tuzilastvo/server/.env
    networks:
      mup_mupnet:
        ipv4_address: 10.5.0.7
  tuzilastvo:
    image: tuzilastvo
    container_name: tuzilastvo
    build:
      context: .
      dockerfile: ./tuzilastvo/Dockerfile
    restart: on-failure
    ports:
      - "8015:8015"
    env_file:
      - ./tuzilastvo/server/.env
    networks:
      mup_mupnet:
        ipv4_address: 10.5.0.8
networks:
  mup_mupnet:
    external: true